name: PyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2.2.2"
        with: { python-version: "3.x" }
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build PyPI Package
        run: python -m build --sdist --wheel --outdir dist/
        env:
          GHA_TEST_VERSION: yes
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish to Distribution PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
